[package]
name = "wallet"
version = "0.1.0"
edition = "2021"
authors = ["Andy.z"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tiny-bip39 = "1.0.0"
tiny-hderive = "0.3.0"
secp256k1 = "0.27.0"
sha3 = "0.10.8"
bs58 = "0.5.0"
